### ISSUE TITLE
Add support for full physical address width

### ISSUE THREAD

**Issue by kkaffes** [project-dune/dune#1]
Add support for full physical address width. It was removed by commit eb2568b7 because it caused unhandled page faults when `dune_vm_page_walk()` function was called. The guest now has access to 16GB proc, mmap and stack memory.

The best starting point is to go back to commit 590fe03 and reproduce the bug by running the benchmark suite.

**Comment by aghosn** [comment]
Hi,
Can you gives us more information about how to reproduce the unhandled page faults that you mentioned (which benchmark, at what point in the execution etc.)?
Thanks!

**Comment by kkaffes** [comment]
Sorry for the delay, you can reproduce it following the steps below:

1.  Checkout commit 590fe03: `git checkout 590f03`
2.  Compile kern and libdune: `make kern libdune`
3.  Compile benchmarks: `cd bench && make`
4.  Insert the kernel module: `insmod kern/dune.ko`
5.  Run bench_dune: `./bench_dune`

**Comment by kkaffes** [comment]
It is probably addressed by #7 . Will test it and close it soon.
