### ISSUE TITLE
Material for understand Intel Virtualization

### ISSUE THREAD

**Issue by rodrigosiqueira** [project-dune/dune#17]
Hi,
A few months ago I read dune's paper published at OSDI'12 and I really liked the project. I started to study Linux Device Driver to better understand dune and help the project. However, I am facing problems to understand the details about Intel Virtualization (specially vmx and ept files). I have read the paper "Intel Virtualization Technology" (cited on dune paper) and the chapter of virtualization from Tanenbaum's book.

Can anyone recommend me some extra material about Intel Virtualization? I am still a little bit lost on this subject.

P.s.: I tried to send this message on project-dune@googlegroups.com since it looks more appropriate, but I couldn't.

**Comment by kkaffes** [comment]
Hi Rodrigo,

Sorry for the late reply. Can you describe in a little more detail why you can't join the mailing list?

**Comment by rodrigosiqueira** [comment]
Hi, I do not remember now. I can try again later.
I required some permission, for someone but I did not receive any notification yet.

**Comment by kkaffes** [comment]
Try signing up here: [https://groups.google.com/forum/#!forum/project-dune](https://groups.google.com/forum/#!forum/project-dune)

**Comment by rodrigosiqueira** [comment]
Applied and waiting.

**Comment by kkaffes** [comment]
Approved. Thanks for your patience.

**Comment by rodrigosiqueira** [comment]
Thanks!
I would like to suggest to add the above link into the README.
