### ISSUE TITLE
test/hello hangs

### ISSUE THREAD

**Issue by gatoWololo** [project-dune/dune#3]
Hello, I was able to successfully compile the project and load the kernel module. When trying to run test/hello it simply hangs...

I'm running on `Ubuntu 16.04  LTS` using kernel version `4.4.0-77-generic`
My CPU is `Intel Core i7-44700MQ CPU @ 2.40 x 8`

I have allowed all permissions for /dev/dune:
   >  ls -ahl /dev/dune
   crwxrwxrwx 1 root root 10, 233 May  9 14:38 /dev/dune

The following is an `strace` of trying to run `test/hello`:
[duneStrace.txt](https://github.com/project-dune/dune/files/987878/duneStrace.txt)

It looks like it gets stuck at ioctl. Any idea what's wrong?

Thanks!

**Comment by kkaffes** [comment]
Hello,

Do you seen any errors in dmesg?
Have you tried running the hello application as root?

**Comment by gatoWololo** [comment]
Huh, running it today it works fine!
I restarted my computer a few more times and it continues to work. I'll report back if I have any further issues.

Extra info from the issue:
1) There was no output when I ran it.
2) I did try running it as root and it still hanged.
3) I did run `dune_req.sh` and it returns yes for everything.
I'm no longer able to reproduce the issue...

**Comment by kkaffes** [comment]
Great! Let me know if it appears again and you manage to reproduce it.
