### ISSUE TITLE
Guest physical address space limited to 36 bits

### ISSUE THREAD

**Issue by prekageo** [project-dune/dune#6]
According to commit eb2568b7e05affa04074f59047b434856ee284f5, Dune was modified and it currently supports only 36 bits of guest physical address space. That is 64 GB. My processor (Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz) supports 46 bits for physical addresses. Is there any reason for this limitation? As a consequence, we can not run IX with your version of Dune.

**Comment by kkaffes** [comment]
Take a look at issue  #1. If we manage to fix this. I will revert the changes. Also, I tested the IX echo server with this version of Dune and it seemed to be working.

**Comment by prekageo** [comment]
I've tested IX with this Dune and it crashes. Do you have more information about how did you test IX?

**Comment by kkaffes** [comment]
You are right. I probably did not compile when testing or misconfigured something. Let's continue this discussion at #1.

**Comment by kkaffes** [comment]
Closing the issue since it is a duplicate from #1
