### ISSUE TITLE
Error for execve system interception

### ISSUE THREAD

**Issue by gatoWololo** [project-dune/dune#8]
Hello, I'm trying to use Dune for it's system call interception capabilities. I'm building on top off the existing sandbox code.

Running the command:

    > ./sandbox /lib64/ld-linux-x86-64.so.2 ./execTest

In quick succession, about 20 times in a row will reliably cause a terrible error.

1) The process stops responding, I'm unable to kill the process with any signal.
2) The kernel module still shows the process as attached, so I'm unable to `rmmod` the kernel module.

    >  lsmod | grep dune
    dune                   36864  1

3) I'm forced to restart the system, which itself is difficult as it either times out or refuses to shutdown (so I'm forced to shut it down by pressing the power button).

See attached for the execTest.txt containing the C code and /var/log/kern.log output.

This happens on a clean "clone" of `master` using the unmodified sandbox code. I have witnessed this behavior on two separate machines both running: `16.04.2 LTS (Xenial Xerus)`.

Thank you for your help.

[kernelError.txt](https://github.com/project-dune/dune/files/1201721/kernelError.txt)
[execTest.txt](https://github.com/project-dune/dune/files/1201727/execTest.txt)

**Comment by gatoWololo** [comment]
This seems to be a bug in the kernel module code for Dune. I have been able to reproduce the error without  the `sandbox` in this minimal code:

The following code produces the error above:
```c
#include<stdio.h>
#include<unistd.h>
#include<err.h>

#include "libdune/dune.h"
#include "libdune/cpu-x86.h"


int main(){
  int ret = dune_init_and_enter();
  if (ret){
    printf("failed to initialize dune\n");
    return ret;
  }

  execl("/bin/ls", "/bin/ls", NULL);
  return 0;
}
```

I am compiling the command as:
```
gcc -O0 -o execTest execTest.c -I dune/ -L dune/libdune/ -l dune
```

Running the executable seems to cause the error fairly reliably, other times it segfaults:
```
>  ./execTest
Hello world!
Segmentation fault
>  ./execTest
Hello world!
# Hangs forever
```

This error is printed from `/var/log/kern.log`: 
[segfaultExecveError.txt](https://github.com/project-dune/dune/files/1223693/segfaultExecveError.txt)

**Comment by gatoWololo** [comment]
Okay, I understand what's wrong. (Please someone correct me if I'm wrong).

All system calls a _duned_ process makes are "sent up" to the kernel module. The kernel module copies the values from the `vcpu`to the CPU registers and runs the system call itself. When it tries to do this for `execve` the process' image is overwritten per semantics of `execve` and `dune` crashes.

**Comment by kkaffes** [comment]
Sorry for the late reply. Yes, I think you are right. After `execve` the process is no longer "duned".
